# Generated by Django 5.2.15 on 2026-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_photo',
            field=models.ImageField(blank=True, null=True, upload_to='appointment_photos/'),
        ),
    ]
